String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Troops!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Skeleton',
    '%4'                    : 'Goblin',
    '%8'                    : 'Archer',
    '%16'                   : 'Barbarian',
    '%32'                   : 'Knight',
    '%64'                   : 'Hog Rider',
    '%128'                  : 'Mini Pekka',
    '%256'                  : 'Giant',
    '%512'                  : 'Prince',
    '%1024'                 : 'Giant Skeleton',
    '%2048'                 : 'Sparky',
    '%4096'                 : 'Golden Knight',
    '%8192'                 : 'Archer Queen',
    '%p0'                   : 'Skeleton',
    '%p4'                   : 'Goblin',
    '%p8'                   : 'Archer',
    '%p16'                  : 'Barbarian',
    '%p32'                  : 'Knight',
    '%p64'                  : 'Hog Rider',
    '%p128'                 : 'Mini Pekka',
    '%p256'                 : 'Giant',
    '%p512'                 : 'Prince',
    '%p1024'                : 'Giant Skeleton',
    '%p2048'                : 'Sparky',
    '%p4096'                : 'Golden Knight',
    '%p8192'                : 'Archer Queen'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Skeleton',
    '%4'                    : 'Goblin',
    '%8'                    : 'Archer',
    '%16'                   : 'Barbarian',
    '%32'                   : 'Knight',
    '%64'                   : 'Hog Rider',
    '%128'                  : 'Mini Pekka',
    '%256'                  : 'Giant',
    '%512'                  : 'Prince',
    '%1024'                 : 'Giant Skeleton',
    '%2048'                 : 'Sparky',
    '%4096'                 : 'Golden Knight',
    '%8192'                 : 'Archer Queen',
    '%p0'                   : 'Skeleton',
    '%p4'                   : 'Goblin',
    '%p8'                   : 'Archer',
    '%p16'                  : 'Barbarian',
    '%p32'                  : 'Knight',
    '%p64'                  : 'Hog Rider',
    '%p128'                 : 'Mini Pekka',
    '%p256'                 : 'Giant',
    '%p512'                 : 'Prince',
    '%p1024'                : 'Giant Skeleton',
    '%p2048'                : 'Sparky',
    '%p4096'                : 'Golden Knight',
    '%p8192'                : 'Archer Queen'
  }

});
